---
title: "Ideas"
author: "Benjamin Skov Kaas-Hansen"
date: "12 Dec 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Execution flow
1. User wants to make a ggplot with our geom
1. 

## Geoms
Above all geoms are added an **outline** layer to give the plot a nice finish
- Body surface
- Bones/skeleton
- Musculature/muscles
- Organs

## Annotation/tweaking (in order of level; the first item is in the back)
- geom + details (= outline)
- horizontal lines with absolute and/or relative frequencies as a stat layer that can be called indepedently

## Other ideas
- In original file each body part in a different layer, so they could be extracted separately? - grImport has a subsetting function...
- Projection
-- front, back, left, right
-- 3D: angle in transversal plane (0 = front; 180 = back)

## Inputs
- Gender (male/female/neutral)
- Division (topographic/dermatomes)
- Choropleth, input options for users:
  - Pre-defined palettes:
    - One-colour (white to this colour)
    - Heat
    - "World map"/terrain (blue to green)
  - Specify #steps ("level of detail") + /colour palette [user-defined, user choosing end-colours, "preinstalled" palettes])
