# \code{humap()} takes relevant specifications from user and uses those to invoke \code{ggplot()}.
# Output: \code{ggplot2} object that the user may modify with, e.g., \code{theme}.

#' Create a humap plot
#'
#' \code{humap} creates a ggplot object, using its own set of "geoms", i.e.,
#' human body oulines on which your data are projected in a heatmap-like
#' fashion. \code{humapr} is an extension of ggplot2, and objects created with
#' the \code{humap} function can be modified with standard ggplot2
#' setting--e.g., calls to \code{theme()}.
#'
#' \code{humapr} uses XML files generated by \code{grImport::PostScriptTrace}, and comes with three levels of details (determined by the \code{setflat} argument).
#'
#' @param data tidy data frame (more under details)
#' @param loc column in data frame containing localisation codes for observations. Character string.
#' @param region body region. Options: body (default), head, neck, arm,
#' @param gender n(eutral) (default), f(emale), m(male)
#' @param type topo(graphical), derma(tomes)
#' @param quality draft, normal (default), high
#' @param side front, back, both
#' @param coding which coding scheme is used, currently supports simple and AIS
#' @param annotate none (defautlt), all, absolute, relative
#'
#' @return
#' A ggplot object with layout settings suitable for the kinds of geoms used in \code{humap}.
#' @export
#'
#' @examples
humap <- function(data = thdat, loc = "loc", region = "body", gender = "male", type = "topo",
                  quality = "normal", side = "front", coding = "simple",
                  annotate = "all") {

    # Safety moves. If invalid argument supplied, defaults chosedn and user prompted.
    valid_args <- list(
        c("region", "body"),
        c("side", "front", "back", "both"),
        c("quality", "normal", "draft", "high"),
        c("annotate", "none", "all", "absolute", "relative")
    )
    for (i in seq(length(valid_args))) {
        if (!get(valid_args[[i]][1]) %in% valid_args[[i]][-1]) {
            message("Invalid ", valid_args[[i]][1], " argument given. Defaults to ", valid_args[[i]][[2]], ".")
            assign(valid_args[[i]][1], valid_args[[i]][2])
        }
    }

    # Set up dedicated environment for the humap, so it's easy to call objects
    # and values within the geom functions
        humapr_env <<- new.env(parent = emptyenv())
        humapr_env$annotate <- annotate

    # Import appropriate XML file
        geom_file <- paste(paste(type, region, gender, side, quality, sep = "_"), "xml", sep = ".")
        humapr_env$surf <- grImport::readPicture(paste0("data/", geom_file))

    # Coding of body regions through crosswalking
        data$mapped_loc <- crosswalk(data, loc, coding, region)

        # User may supply a function that changes (i.e., simplifies) the coding, e.g., merging facial sub-regions
        if (exists("humapr_env$simplify_coding")) crosswalk[humapr_env$simplify_coding[1]] <- humapr_env$simplify_coding[2]

    ggplot(data, aes(x = mapped_loc, fill = -..count..)) +
        eval(call(paste0("geom_", region))) +
        theme(axis.title = element_blank(),
              axis.text = element_blank(),
              axis.line = element_blank(),
              axis.ticks = element_blank(),
              panel.grid = element_blank(),
              legend.title = element_blank())
}
